# Generated by Django 5.2.13 on 2026-04-26 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_role', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['nombre_role'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.role')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['username'],
            },
        ),
    ]
